### PR TITLE
Cleanup  requests dependency and move to examples group

### PR DESCRIPTION
**Pull request by izofat**

### CODE REVIEW

**Comment by aclerc** [comment]
thanks @izofat ! Sorry the issue was not very detailed, I think another point to address would be the README instructions, for example `pip install -e .[dev] # or .[jupyter,dev] if you want jupyter dependencies as well` might change to `pip install -e .[dev] # or .[examples,dev] if you want dependencies for running the examples as well` and in that case examples needs the jupyter dependencies. A simple 'all' dependency option would be nice too

**Comment by izofat** [comment]
Thanks for the feedback.
I moved the jupyter group to examples.
Added an all group for users that want to download all dependencies.
And updated the README file.
I wrote a part for users that want to just install example dependencies.

**Comment by aclerc** [comment]
thanks you, the README looks better. I think you can define groups from other groups rather than repeating dependencies which should make pyproject.toml more maintainable, could you please have a look? https://peps.python.org/pep-0735/#example-dependency-groups-table
do the examples run ok when you install [examples] and [all]?

**Comment by izofat** [comment]
@aclerc
I searched for grouping the dependencies but it's not possible in pyproject.toml if you check the link you mentioned depency-groups not for downloading.
Repeating the dependencies does not look good but we have to i guess.
Examples run perfectly fine with [examples] and [all].

**Review by aclerc — APPROVED** [review]

**Comment by aclerc** [comment]
> @aclerc I searched for grouping the dependencies but it's not possible in pyproject.toml if you check the link you mentioned depency-groups are not for installing. Repeating the dependencies does not look good but we have to i guess. If you find anything about grouping the dependencies feel free to commit the branch. Examples run perfectly fine with [examples] and [all]. I would be thankful to contribute to project especially the python part. Don't bother to mention me in the issue

@izofat I found a solution after checking how the OpenOA repo does it https://github.com/NREL/OpenOA/blob/main/pyproject.toml

**Pull request merged**
